#!/usr/bin/env python

import sys

from rqt_freq_monitor.my_module import FrequencyMonitor
from rqt_gui.main import Main
    

plugin = 'rqt_freq_monitor'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
